name: SUKOON

on:
  push:
    branches:
      - master   # change to 'main' if that's your default branch

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello from my side"
